# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_euclidean_distance <- function(vec1, vec2) {
    .Call('_glados_get_euclidean_distance', PACKAGE = 'glados', vec1, vec2)
}

